version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore LuaInstaller.sln
build:
  project: LuaInstaller.sln
  verbosity: minimal
on_success:
- ps: >-
    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe list-lua

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe list-vs

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe list-vs-x86

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe list-vs-x64

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe list-win-sdk

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe "/?"

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe help

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe install dest-dir=lua

	& lua\bin\lua.exe -v

	Remove-Item .\lua -Recurse -Force

    & LuaInstaller.Console\bin\Release\LuaInstaller.Console.exe install dest-dir=lua version=5.1.5
	
	& lua\bin\lua.exe -v

	Remove-Item .\lua -Recurse -Force