version: 1.0.{build}
install:
- ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
- ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -Version "6.0.301" -InstallDir "$env:ProgramFiles\dotnet"'
build_script:
- ps: .\appveyor.ps1
build: off