version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore LuaInstaller.sln
build:
  verbosity: minimal
dotnet_csproj:
  file: '**\*.csproj'
on_success:
- ps: .\appveyor.ps1