version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore LuaInstaller.sln
build:
  project: LuaInstaller.sln
  verbosity: minimal
on_success:
- ps: .\appveyor.ps1