name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  release-x64:
    name: Release x64
    uses: ./.github/workflows/release.yaml
    if: ${{ github.ref_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
    with:
      arch: x64
    needs: build
  
  release-x86:
    name: Release x86
    uses: ./.github/workflows/release.yaml
    if: ${{ github.ref_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
    with:
      arch: x86
    needs: build

  ci:
    name: CI
    runs-on: windows-latest
    needs:
      - build
      - release-x64
      - release-x86
    
    steps:
      - name: CI
        run: |
          $color = (0x1b -as [char]) + "[35m";
          Write-Host "Finishing the ${color}CI";