name: CI

on:
  push:
    paths-ignore:
      - "docs"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs"
      - "**/*.md"

jobs:

  lfs:
    name: LuaFileSystem (${{ matrix.lua-version }} ${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - lua-version: 5.1.5
            arch: x86
            os: windows-latest

          - lua-version: 5.2.4
            arch: x86
            os: windows-latest

          - lua-version: 5.3.6
            arch: x86
            os: windows-latest

          - lua-version: 5.4.7
            arch: x86
            os: windows-latest

          - lua-version: 5.1.5
            arch: x64
            os: windows-latest

          - lua-version: 5.2.4
            arch: x64
            os: windows-latest

          - lua-version: 5.3.6
            arch: x64
            os: windows-latest

          - lua-version: 5.4.7
            arch: x64
            os: windows-latest

          - lua-version: 5.1.5
            arch: arm64
            os: windows-11-arm

          - lua-version: 5.2.4
            arch: arm64
            os: windows-11-arm

          - lua-version: 5.3.6
            arch: arm64
            os: windows-11-arm

          - lua-version: 5.4.7
            arch: arm64
            os: windows-11-arm

    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: ${{ matrix.lua-version }}
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}

  lgi:
    name: LGI (${{ matrix.lua-version }} GTK ${{ matrix.gtk-major-version }})
    strategy:
      matrix:
        lua-version:
          - 5.1.5
          - 5.2.4
          - 5.3.6
          - 5.4.7
        gtk-major-version:
          - 3
          - 4

    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: ${{ matrix.lua-version }}
      gtk-major-version: ${{ matrix.gtk-major-version }}
