name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:

  lfs-515-x64:
    name: LuaFileSystem (5.1.5 x64)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.1.5
      arch: x64
  
  lfs-515-x86:
    name: LuaFileSystem (5.1.5 x86)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.1.5
      arch: x86
      
  lfs-524-x64:
    name: LuaFileSystem (5.2.4 x64)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.2.4
      arch: x64
  
  lfs-524-x86:
    name: LuaFileSystem (5.2.4 x86)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.2.4
      arch: x86
  
  lfs-536-x64:
    name: LuaFileSystem (5.3.6 x64)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.3.6
      arch: x64
  
  lfs-536-x86:
    name: LuaFileSystem (5.3.6 x86)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.3.6
      arch: x86
  
  lfs-547-x64:
    name: LuaFileSystem (5.4.7 x64)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.4.7
      arch: x64
  
  lfs-547-x86:
    name: LuaFileSystem (5.4.7 x86)
    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: 5.4.7
      arch: x86
  
  lgi-515-gtk3:
    name: LGI (5.1.5 GTK 3)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.1.5
      gtk-major-version: 3

  lgi-515-gtk4:
    name: LGI (5.1.5 GTK 4)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.1.5
      gtk-major-version: 4

  lgi-524-gtk3:
    name: LGI (5.2.4 GTK 3)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.2.4
      gtk-major-version: 3

  lgi-524-gtk4:
    name: LGI (5.2.4 GTK 4)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.2.4
      gtk-major-version: 4

  lgi-536-gtk3:
    name: LGI (5.3.6 GTK 3)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.3.6
      gtk-major-version: 3

  lgi-536-gtk4:
    name: LGI (5.3.6 GTK 4)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.3.6
      gtk-major-version: 4

  lgi-547-gtk3:
    name: LGI (5.4.7 GTK 3)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.4.7
      gtk-major-version: 3

  lgi-547-gtk4:
    name: LGI (5.4.7 GTK 4)
    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: 5.4.7
      gtk-major-version: 4

  release-x64:
    name: Release x64
    uses: ./.github/workflows/release.yaml
    if: ${{ github.ref_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
    with:
      arch: x64
    needs:
      - lfs-515-x64
      - lfs-515-x86
      - lfs-524-x64
      - lfs-524-x86
      - lfs-536-x64
      - lfs-536-x86
      - lfs-547-x64
      - lfs-547-x86
      - lgi-515-gtk3
      - lgi-515-gtk4
      - lgi-524-gtk3
      - lgi-524-gtk4
      - lgi-536-gtk3
      - lgi-536-gtk4
      - lgi-547-gtk3
      - lgi-547-gtk4
  
  release-x86:
    name: Release x86
    uses: ./.github/workflows/release.yaml
    if: ${{ github.ref_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
    with:
      arch: x86
    needs: 
      - lfs-515-x64
      - lfs-515-x86
      - lfs-524-x64
      - lfs-524-x86
      - lfs-536-x64
      - lfs-536-x86
      - lfs-547-x64
      - lfs-547-x86
      - lgi-515-gtk3
      - lgi-515-gtk4
      - lgi-524-gtk3
      - lgi-524-gtk4
      - lgi-536-gtk3
      - lgi-536-gtk4
      - lgi-547-gtk3
      - lgi-547-gtk4

  ci:
    name: CI
    runs-on: windows-latest
    needs:
      - lfs-515-x64
      - lfs-515-x86
      - lfs-524-x64
      - lfs-524-x86
      - lfs-536-x64
      - lfs-536-x86
      - lfs-547-x64
      - lfs-547-x86
      - lgi-515-gtk3
      - lgi-515-gtk4
      - lgi-524-gtk3
      - lgi-524-gtk4
      - lgi-536-gtk3
      - lgi-536-gtk4
      - lgi-547-gtk3
      - lgi-547-gtk4
      - release-x64
      - release-x86
    
    steps:
      - name: CI
        run: |
          $color = (0x1b -as [char]) + "[35m";
          Write-Host "Finishing the ${color}CI";