name: CI

on:
  push:
    paths-ignore:
      - "docs"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs"
      - "**/*.md"

jobs:

  lfs:
    name: LuaFileSystem (${{ matrix.lua-version }} ${{ matrix.arch }})
    strategy:
      matrix:
        lua-version:
          - 5.1.5
          - 5.2.4
          - 5.3.6
          - 5.4.7
        arch:
          - x64
          - x86

    uses: ./.github/workflows/lfs.yaml
    with:
      lua-version: ${{ matrix.lua-version }}
      arch: ${{ matrix.arch }}

  lfs-arm64:
    name: LuaFileSystem (${{ matrix.lua-version }} ARM64)
    strategy:
      matrix:
        lua-version:
          - 5.1.5
          - 5.2.4
          - 5.3.6
          - 5.4.7

    uses: ./.github/workflows/lfs-arm64.yaml
    with:
      lua-version: ${{ matrix.lua-version }}

  lgi:
    name: LGI (${{ matrix.lua-version }} GTK ${{ matrix.gtk-major-version }})
    strategy:
      matrix:
        lua-version:
          - 5.1.5
          - 5.2.4
          - 5.3.6
          - 5.4.7
        gtk-major-version:
          - 3
          - 4

    uses: ./.github/workflows/lgi.yaml
    with:
      lua-version: ${{ matrix.lua-version }}
      gtk-major-version: ${{ matrix.gtk-major-version }}
